class Metric():
    
    def __init__(self, train, test, GetRecommendation): # 初始化
        ...
    def getRec(self): # 为test中的每个用户进行推荐
        ...
    def precision(self): # 定义精确率指标计算方式
        ...
    def recall(self): # 定义召回率指标计算方式
        ...
    def coverage(self): # 定义覆盖率指标计算方式
        ...
    def popularity(self): # 定义新颖度指标计算方式
        ...
    def eval(self): # 输出评价指标
        ...