class Metric():
    
    def __init__(self, train, test, GetRecommendation):
        ...
    def getRec(self):
        ...
    def precision(self):
        ...
    def recall(self):
        ...
    def coverage(self):
        ...
    def popularity(self):
        ...
    def eval(self):
        ...